name: Build

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.gitattributes'
      - '.github/workflows/**'
      - '!.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 21, x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: Set executable flag on gradlew
        working-directory: ./tooling
        run: chmod +x gradlew
      - name: Execute tests
        working-directory: ./tooling
        env:
          GH_PACKAGES_READ_TOKEN: ${{ secrets.PACKAGES_READ_TOKEN }}
        run: ./gradlew test
      - name: Workflow housekeeping
        if: ${{ matrix.java == 21 }}
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 30
          keep_minimum_runs: 1